### PR TITLE
Added license data

### PR DESCRIPTION
**Pull request by bogdanm**

### CODE REVIEW

**Comment by bogdanm** [comment]
@0xc0170

**Comment by 0xc0170** [comment]
Do we need that license file there? And what about using SPDX compatible license headers?

**Comment by bogdanm** [comment]
Do we need which license file? `LICENSE`? Sure we do.
Why are the headers non-SPDX compatible?

**Comment by 0xc0170** [comment]
> Why are the headers non-SPDX compatible?

https://github.com/ARMmbed/mbed-drivers/blob/master/mbed-drivers/AnalogIn.h#L3

**Comment by bogdanm** [comment]
Ah, THAT's why! OK, fixed :)

**Comment by 0xc0170** [comment]
LGTM

**Pull request merged**
